import { create } from 'zustand'

const useStore = create((set) => ({
  popA: 1,
  taxaA: 1,
  kA: 1,
  popB: 1,
  taxaB: 1,
  kB: 1,
  popC: 1,
  taxaC: 1,
  kC: 1,
  popD: 1,
  taxaD: 1,
  kD: 1,
  popE: 1,
  taxaE: 1,
  kE: 1,
  ab: 1,
  ac: 1,
  ad: 1,
  ae: 1,
  bc: 1,
  bd: 1,
  be: 1,
  cd: 1,
  ce: 1,
  de: 1,
  maxValue: 0,
  linhas: 10000000,
  setMaxValue: () => set(state => ({maxValue: (state.kA + state.kB + state.kC + state.kD + state.kE)/5 + 10000})),
  setPopA: (value) => set({ popA: value }),
  setPopB: (value) => set({ popB: value }),
  setPopC: (value) => set({ popC: value }),
  setPopD: (value) => set({ popD: value }),
  setPopE: (value) => set({ popE: value }),
  setTaxaA: (value) => set({ taxaA: value }),
  setTaxaB: (value) => set({ taxaB: value }),
  setTaxaC: (value) => set({ taxaC: value }),
  setTaxaD: (value) => set({ taxaD: value }),
  setTaxaE: (value) => set({ taxaE: value }),
  setKa: (value) => set({ kA: value }),
  setKb: (value) => set({ kB: value }),
  setKc: (value) => set({ kC: value }),
  setKd: (value) => set({ kD: value }),
  setKe: (value) => set({ kE: value }),
  setab: (value) => set({ ab: value }),
  setac: (value) => set({ ac: value }),
  setad: (value) => set({ ad: value }),
  setae: (value) => set({ ae: value }),
  setbc: (value) => set({ bc: value }),
  setbd: (value) => set({ bd: value }),
  setbe: (value) => set({ be: value }),
  setcd: (value) => set({ cd: value }),
  setce: (value) => set({ ce: value }),
  setde: (value) => set({ de: value }), 
  setLinhas: (value) => set({ linhas: value }), 
}))

export default useStore
